parameters:
#    web_gate.login: ~
#    web_gate.password: ~
    web_gate.soap.environment: dev
    web_gate.soap.connection_timeout: 15

    web_gate.logger.logging_max_files: 0
    web_gate.logger.logging_level: 100     # 100 => 'DEBUG', 200 => 'INFO', 250 => 'NOTICE', 300 => 'WARNING', 400 => 'ERROR', 500 => 'CRITICAL', 550 => 'ALERT', 600 => 'EMERGENCY'

    web_gate.rest.host: ~
    web_gate.rest.resource: ~
    web_gate.rest.login: ~
    web_gate.rest.password: ~
